package vs.sociemutuapresentacion.ui;

import javax.swing.JOptionPane;
import vs.sociemutuadominio.models.Iglesia;
import vs.sociemutuapresentacion.enums.Operations;

/**
 * Vista para administrar a las iglesias.
 * @author Samuel Vega
 */
public class IglesiaView extends javax.swing.JFrame {
    private final Operations operacion;
    private Iglesia iglesia;

    /**
     * Creates new form IglesiaView
     * @param iglesia Iglesia que se utilizara en la ventana.
     * @param operacion La operacion que se va a realizar en la ventana actual.
     */
    public IglesiaView(Iglesia iglesia, Operations operacion) {
        this.iglesia = iglesia;
        this.operacion = operacion;
        
        initComponents();
        
        this.manejarElementosVisuales();
    }
    
    private void manejarElementosVisuales() {
        if(operacion.equals(Operations.GUARDAR)) {
            this.btnAceptar.setText("Guardar");
            this.btnRestaurar.setEnabled(false);
        }
        
        if(operacion.equals(Operations.ACTUALIZAR)) {
            this.btnAceptar.setText("Actualizar");
            this.rescatarInformacion();
        }
        
        if(operacion.equals(Operations.ELIMINAR)) {
            this.btnAceptar.setText("Eliminar");
            this.btnRestaurar.setVisible(false);
            
            this.rescatarInformacion();
            
            this.txtPastor.setEnabled(false);
            this.txtSaldo.setEnabled(false);
            this.txtNombre.setEnabled(false);
        }
    }
    
    private void rescatarInformacion() {
        this.txtNombre.setText(iglesia.getNombre());
        this.txtPastor.setText(iglesia.getPastor());
        this.txtSaldo.setText(String.valueOf(iglesia.getSaldo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIglesia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPastor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        btnEditSocios = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnRestaurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Iglesias");

        lblIglesia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIglesia.setText("Iglesia");

        jLabel1.setText("Pastor:");

        jLabel2.setText("Saldo:  $");

        btnEditSocios.setText("Editar Socios...");

        btnAceptar.setText("Actualizar");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jLabel3.setText("Nombre:");

        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(this::btnRestaurarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPastor)
                            .addComponent(txtSaldo)
                            .addComponent(txtNombre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditSocios))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRestaurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAceptar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIglesia)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIglesia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPastor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditSocios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar)
                    .addComponent(btnRestaurar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Seguro que desea salir?", "Iglesia | Cancelar", JOptionPane.YES_NO_OPTION);
        
        if(response == 0) dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Seguro que desea restaurar los valores?", "Iglesia | Restaurar", JOptionPane.YES_NO_OPTION);
        
        if(response == 0) this.rescatarInformacion();
    }//GEN-LAST:event_btnRestaurarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditSocios;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblIglesia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPastor;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
