package vs.sociemutuapresentacion.godly;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import vs.sociemutuadominio.interfaces.IIglesiaRepository;
import vs.sociemutuadominio.models.Iglesia;
import vs.sociemutuadto.dto.IglesiaDTO;
import vs.sociemutuadto.mapper.IglesiaDTOMapper;
import vs.sociemutuapersistencia.persistence.IglesiaRepositoryImpl;
import vs.sociemutuapresentacion.enums.Operations;
import vs.sociemutuapresentacion.ui.IglesiaView;
import vs.sociemutuapresentacion.ui.TableView;

/**
 * Hecha para testear de diferentes formas las ventanas
 * @author Samuel Vega
 */
public class GodView extends javax.swing.JFrame {
    private final IIglesiaRepository iglesiaRepo;
    private TableView tableView;
    private IglesiaDTO testIg;

    /**
     * Creates new form GodClass
     */
    public GodView() {
        this.iglesiaRepo = new IglesiaRepositoryImpl();
        this.tableView = new TableView();
        this.testIg = null;
        
        initComponents();
    }
    
    private boolean faltaEntidadPrueba(String entidad) {
        if(entidad.equalsIgnoreCase("iglesia")) {
            if(testIg == null) {
                this.MostrarError("No existe ninguna Iglesia sobre cual probar esta ventana.\nPor favor, presione \"Obtener una Iglesia\" para acceder a esta ventana.");
                return true;
            }
        }
        
        return false;
    }
    
    private void MostrarError(String info) {
        JOptionPane.showMessageDialog(
            this, 
            info,
            "GOD | Cuidado de Errores",
            JOptionPane.INFORMATION_MESSAGE
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iglesiasPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnISave = new javax.swing.JButton();
        btnIUpdate = new javax.swing.JButton();
        BtnIRemove = new javax.swing.JButton();
        btnIChoose = new javax.swing.JButton();
        btnShowITbl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GOD Controls | All Operations At One");

        iglesiasPanel.setBackground(new java.awt.Color(204, 204, 204));
        iglesiasPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Iglesias");

        btnISave.setText("Abrir \"Guardar\"");
        btnISave.addActionListener(this::btnISaveActionPerformed);

        btnIUpdate.setText("Abrir \"Actualizar\"");
        btnIUpdate.addActionListener(this::btnIUpdateActionPerformed);

        BtnIRemove.setText("Abrir \"Eliminar\"");
        BtnIRemove.addActionListener(this::BtnIRemoveActionPerformed);

        btnIChoose.setText("Obtener una Iglesia");
        btnIChoose.addActionListener(this::btnIChooseActionPerformed);

        btnShowITbl.setText("Mostrar tabla de Iglesias");
        btnShowITbl.addActionListener(this::btnShowITblActionPerformed);

        javax.swing.GroupLayout iglesiasPanelLayout = new javax.swing.GroupLayout(iglesiasPanel);
        iglesiasPanel.setLayout(iglesiasPanelLayout);
        iglesiasPanelLayout.setHorizontalGroup(
            iglesiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iglesiasPanelLayout.createSequentialGroup()
                .addGroup(iglesiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(iglesiasPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1))
                    .addGroup(iglesiasPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(iglesiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIChoose)
                            .addComponent(BtnIRemove)
                            .addComponent(btnIUpdate)
                            .addComponent(btnISave)))
                    .addGroup(iglesiasPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnShowITbl)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        iglesiasPanelLayout.setVerticalGroup(
            iglesiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iglesiasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnISave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnIRemove)
                .addGap(18, 18, 18)
                .addComponent(btnIChoose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowITbl)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iglesiasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iglesiasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnISaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnISaveActionPerformed
        IglesiaView iv = new IglesiaView(new IglesiaDTO(), Operations.GUARDAR);
        iv.setVisible(true);
    }//GEN-LAST:event_btnISaveActionPerformed

    private void btnIUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIUpdateActionPerformed
        if(this.faltaEntidadPrueba("iglesia")) return;
        IglesiaView iv = new IglesiaView(testIg, Operations.ACTUALIZAR);
        iv.setVisible(true);
    }//GEN-LAST:event_btnIUpdateActionPerformed

    private void BtnIRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIRemoveActionPerformed
        if(this.faltaEntidadPrueba("iglesia")) return;
        IglesiaView iv = new IglesiaView(testIg, Operations.ELIMINAR);
        iv.setVisible(true);
    }//GEN-LAST:event_BtnIRemoveActionPerformed

    private void btnIChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIChooseActionPerformed
        Long chosenId = 0L;
        String response = JOptionPane.showInputDialog(
            this,
            "Ingrese el ID de la iglesia: ",
            "GOD | Obtener una iglesia",
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        
        if (response != null && !response.trim().isEmpty()) {
            try {
                chosenId = Long.valueOf(response.trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                    this,
                    "Por favor, ingrese un número válido.",
                    "GOD | Entrada inválida",
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        }

        testIg = IglesiaDTOMapper.toDto(this.iglesiaRepo.buscarPorId(chosenId));
        
        if(testIg == null) {
            JOptionPane.showMessageDialog(
                this,
                "No hay ninguna Iglesia con ese ID: " + chosenId,
                "GOD | ID inexistente",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        JOptionPane.showMessageDialog(this, 
                "Iglesia Obtenida. \n"
                + "Nombre: \"" + testIg.getNombre() + "\" \n"
                + "Saldo: $ " + testIg.getSaldo() + "\n"
                + "Pastor: \"" + testIg.getPastor() + "\" \n",
                "GOD | Iglesia Obtenida",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_btnIChooseActionPerformed

    private void btnShowITblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowITblActionPerformed
        List<IglesiaDTO> iglesias = new ArrayList();
        
        for (Iglesia iglesia : this.iglesiaRepo.obtenerTodos()) {
            iglesias.add(IglesiaDTOMapper.toDto(iglesia));
        }
        
        tableView.cargarTablaIglesias(iglesias);
        tableView.setVisible(true);
    }//GEN-LAST:event_btnShowITblActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIRemove;
    private javax.swing.JButton btnIChoose;
    private javax.swing.JButton btnISave;
    private javax.swing.JButton btnIUpdate;
    private javax.swing.JButton btnShowITbl;
    private javax.swing.JPanel iglesiasPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
